(deffacts MAIN::the-restaurant-list
	(restaurant (name "Restoran A") (isSmoker TRUE) (minBudget 1000) (maxBudget 2000) (dresscode "casual") (hasWifi TRUE))
	(restaurant (name "Restoran B") (isSmoker FALSE) (minBudget 1200) (maxBudget 2500) (dresscode "informal") (hasWifi TRUE))
	(restaurant (name "Restoran C") (isSmoker TRUE) (minBudget 2000) (maxBudget 4000) (dresscode "formal") (hasWifi FALSE))
	(restaurant (name "Restoran D") (isSmoker FALSE) (minBudget 500) (maxBudget 1400) (dresscode "formal") (hasWifi FALSE))
	(restaurant (name "Restoran E") (isSmoker TRUE) (minBudget 1000) (maxBudget 2000) (dresscode "formal" "casual") (hasWifi TRUE))
	(restaurant (name "Restoran F") (isSmoker FALSE) (minBudget 2500) (maxBudget 5000) (dresscode "informal") (hasWifi TRUE))
	(restaurant (name "Restoran G") (isSmoker TRUE) (minBudget 1300) (maxBudget 3000) (dresscode "casual") (hasWifi TRUE))
	(restaurant (name "Restoran H") (isSmoker FALSE) (minBudget 400) (maxBudget 1000) (dresscode "informal") (hasWifi FALSE))
)